server:
  port: 8081

spring:
  mail:
    #smtp服务主机  qq邮箱为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1758953093@qq.com
    #授权码
    password: bymzqtfmruteeehc
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://10.1.87.70:3306/squeezer?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000    # 配置间隔多久才进行一次监测，监测需要关闭的空闲连接，单位时毫秒
      min-evictable-idle-time-millis: 60000       # 配置一个连接在池中最小生存的时间
      validation-query: SELECT 1                 # 用来监测连接是否有效的sql，要求是一个查询语句
      test-while-idle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false


##赋值
test:
  list: distribute_task,ost_ed,avs_ed
  val: 100


